# frozen_string_literal: true

source 'https://rubygems.org'
gem 'activerecord', :require => 'active_record'
gem 'dotenv', '~> 2.2', '>= 2.2.1'
gem 'heroku', '~> 3.99'
gem 'jwt', '~> 1.5', '>= 1.5.6'
gem 'oauth2'
gem 'pg', '~> 0.18.4'
gem 'pry', '~> 0.10.4'
gem 'rake', '~> 12.0'
gem 'rubocop', '~> 0.49.1'
gem 'sinatra'
gem 'sinatra-activerecord', :require => 'sinatra/activerecord'
gem 'sinatra-flash', '~> 0.3.0'
gem 'thin', '~> 1.7', '>= 1.7.2'
gem 'vk', '~> 0.6.5.53'
