# frozen_string_literal: true
source 'https://rubygems.org'
gem 'activerecord', :require => 'active_record'
gem 'heroku', '~> 3.99'
gem 'jwt', '~> 1.5', '>= 1.5.6'
gem 'oauth2'
gem 'pg', '~> 0.18.4'
gem 'rake', '~> 12.0'
gem 'sinatra'
gem 'sinatra-activerecord', :require => 'sinatra/activerecord'
gem 'thin', '~> 1.7', '>= 1.7.2'
gem 'vk', '~> 0.6.5.53'
